# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c30c46d717d3eb9481a1bb71a2bd1c246b68366668bc9a75ad37621a97fbbc2e0b0df05280515a4ff6ff97bb328c145d4399aa130426ced6c8e14fb9c19358

test:
  secret_key_base: 00d45f6038352ba84d5da77113f68cb7af9a7097c2d1b37778680968f36ef7895c1e0240a307691acdcec80d6382c97bb17afd7143065cef7b6e7981733347c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
